### ISSUE TITLE
segfault in destructor

### ISSUE THREAD

**Issue by mikedh** [scopatz/pyembree#22]
Thanks for the great package! In a [trimesh issue](https://github.com/mikedh/trimesh/issues/550) someone posted a backtrace that looked like it was occurring in the pyembree destructor, I was wondering if you'd ever seen anything similar?

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) py-bt
Traceback (most recent call first):
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fffd8ab7c30 in embree::avx::TriangleMeshISA::~TriangleMeshISA() ()
   from /usr/local/lib/libembree.so.2
#2  0x00007fffd850002f in embree::Scene::~Scene() ()
   from /usr/local/lib/libembree.so.2
#3  0x00007fffd8500179 in embree::Scene::~Scene() ()
   from /usr/local/lib/libembree.so.2
#4  0x00007fffd84c3cc5 in rtcDeleteScene () from /usr/local/lib/libembree.so.2
#5  0x00007fffd992474c in __pyx_pf_8pyembree_12rtcore_scene_11EmbreeScene_4__dealloc__ (__pyx_v_self=0x7fffd3166490) at pyembree/rtcore_scene.cpp:3434
#6  __pyx_pw_8pyembree_12rtcore_scene_11EmbreeScene_5__dealloc__ (
    __pyx_v_self=<pyembree.rtcore_scene.EmbreeScene at remote 0x7fffd3166490>)
    at pyembree/rtcore_scene.cpp:3419
#7  __pyx_tp_dealloc_8pyembree_12rtcore_scene_EmbreeScene (
    o=<pyembree.rtcore_scene.EmbreeScene at remote 0x7fffd3166490>)
    at pyembree/rtcore_scene.cpp:6042
#8  0x00000000004fc70f in PyDict_Clear () at ../Objects/dictobject.c:946
#9  0x00000000005419b9 in dict_tp_clear.lto_priv.332 (op=<optimized out>)
    at ../Objects/dictobject.c:2152
#10 0x000000000049ca0f in delete_garbage (
    old=0x8fa280 <generations.lto_priv+96>, collectable=0x7fffffffdb40)
    at ../Modules/gcmodule.c:820
#11 collect.lto_priv () at ../Modules/gcmodule.c:984
---Type <return> to continue, or q <return> to quit---
#12 0x00000000004f9ade in PyGC_Collect () at ../Modules/gcmodule.c:1440
#13 0x00000000004f8d7f in Py_Finalize () at ../Python/pythonrun.c:448
#14 0x00000000004936f2 in Py_Main () at ../Modules/main.c:665
#15 0x00007ffff7810830 in __libc_start_main (main=0x4932b0 <main>, argc=2, 
    argv=0x7fffffffddd8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffddc8)
    at ../csu/libc-start.c:291
#16 0x00000000004931d9 in _start ()
```

**Comment by scopatz** [comment]
Thanks @mikedh! I haven't seen that.  But if there is a fix that you find, PRs welcome!
